---
- hosts: all
  roles:
    - role: knopki.timezone
      timezone: "Europe/Moscow"
  tasks:
    # Install packages
    - apt: update_cache=yes cache_valid_time=86400
    - apt: upgrade=dist
    - apt: name="{{ item }}" state=latest
      with_items:
        - cifs-utils
        - psmisc 
        - tree
        - net-tools
        - nano
        - wget
        - git
        - curl
        - nmap
        - mtr 
        - rsync
        - whois
        - htop
        - aptitude
        - zsh
        - iperf
        - apt-transport-https
        - lsb-release
        - php5-cli
        - byobu
    - apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
    - apt_repository: repo="deb https://apt.dockerproject.org/repo debian-jessie main" state=present update_cache=yes
    - apt: name="docker-engine=1.8.*" state=present
    - apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
    - apt_repository: repo="deb https://deb.nodesource.com/node_0.12 jessie main" state=present update_cache=yes
    - apt: name="nodejs" state=latest

    # Setup ssh
    - file: path=/home/vagrant/.ssh state=directory owner=vagrant
    - file: path=/vagrant/home/.ssh state=directory
    - file: path=/vagrant/home/.ssh/known_hosts state=touch
    - file: src=/vagrant/home/.ssh/known_hosts path=/home/vagrant/.ssh/known_hosts state=link
        
    # Install oh-my-zsh
    - git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh depth=1
    - file: path=/home/vagrant/.oh-my-zsh recurse=yes owner=vagrant
    - user: name=vagrant shell=/bin/zsh
    - stat: path=/vagrant/home/.zshrc
      register: zshrc_stat
    - copy: src=/home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template dest=/vagrant/home/.zshrc
      when: not zshrc_stat.stat.exists
    - file: src=/vagrant/home/.zshrc path=/home/vagrant/.zshrc state=link

    # Other symlinks
    - file: path=/vagrant/home/.config state=directory
    - file: src=/vagrant/home/.config path=/home/vagrant/.config state=link
    - file: path=/vagrant/home/.docker state=directory
    - file: src=/vagrant/home/.docker path=/home/vagrant/.docker state=link
    - file: src=/vagrant/home/Development path=/home/vagrant/Development state=link
    - file: src=/vagrant/home/.gitconfig path=/home/vagrant/.gitconfig state=link
    
    # Docker additions
    - stat: path=/usr/local/bin/docker-machine
      register: docker_machine_exists
    - get_url: url=https://github.com/docker/machine/releases/download/v0.4.1/docker-machine_linux-amd64 dest=/usr/local/bin/docker-machine mode=0755
      when: not docker_machine_exists.stat.exists
    - stat: path=/usr/local/bin/docker-compose
      register: docker_compose_exists
    - get_url: url=https://github.com/docker/compose/releases/download/1.4.0/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755
      when: not docker_compose_exists.stat.exists
    - user: name=vagrant append=yes groups=docker
    
    # PHP additions
    - stat: path=/usr/local/bin/composer
      register: composer_exists
    - get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755
      when: not composer_exists.stat.exists

    # NodeJS additions
    - npm: name=bower global=yes state=present
      sudo: yes